server:
  port: 8081

spring:
  application:
    name: offer-service

services:
  inventory:
    url: http://localhost:8083
  pricing:
    url: http://localhost:8082

management:
  endpoints:
    web:
      exposure:
        include: health,info
